libraries:
  active: true
  ForbiddenPublicDataClass:
    active: true
    ignorePackages:
      - '*.internal'
      - '*.internal.*'
  LibraryCodeMustSpecifyReturnType:
    active: true
  LibraryEntitiesShouldNotBePublic:
    active: true
